name: Test Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Deploy
        run: |
          bash ./build.sh
